# FastApiExample

Notes: 

 - I receive a strange error when posting to the /claims endpoint. The entry saves correctly but I receive the error:
 sqlalchemy.orm.exc.DetachedInstanceError: Instance <Claim at 0xffff9bdc7a40> is not bound to a Session; attribute refresh operation cannot proceed (Background on this error at: https://sqlalche.me/e/14/bhk3)

 

